# Identificadores del proyecto en SonarCloud 
sonar.projectKey=SebJoq21_Proyecto_EcoAcopio
sonar.organization=sebjoq21

sonar.sources=backend/src,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts,**/*.spec.ts,frontend/cypress/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info